theme: jekyll-theme-tactile
title: WebHelp Responsive Custom Footer plugin
description: WebHelp Responsive customization plugin to add copyright information and generation time in the WebHelp Responsive footer.
